In [2]:
import numpy as np
import torch

In [10]:
a = torch.tensor([[1, 2, 3], [0, 1, 2]], dtype=torch.float)
torch.norm(a, dim=1)

tensor([3.7417, 2.2361])

In [32]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

device='cpu'

class DistMulti(nn.Module):

    def __init__(self, embedding_dim, relation_size, entity_size):
        super(DistMulti, self).__init__()
        self.embedding_dim = embedding_dim

        self.entity_embed = nn.Embedding(entity_size, embedding_dim)
        self.relation_embed = nn.Embedding(relation_size, embedding_dim)
        
        for param in self.parameters():
            print(param)
            r_s = param.sum(dim=1)
            param = param / r_s
            
        for param in self.parameters():
            print(param)
        
    def forward(self, head, tail, relation):
        head_embed = self.entity_embed(head)
        tail_embed = self.entity_embed(tail)
        relation_embed = self.relation_embed(relation)
        
        score = torch.sum(head_embed * tail_embed * relation_embed, axis=1)
        score = torch.sigmoid(score)
        
        return score
    
    def predict(self, user_tensor, item_tensor):
        return 0

In [33]:
model = DistMulti(2, 2 ,2)

Parameter containing:
tensor([[-0.3902,  0.2747],
        [-0.5827,  0.4113]], requires_grad=True)
Parameter containing:
tensor([[ 1.0853,  0.0631],
        [-0.3021, -0.0524]], requires_grad=True)
Parameter containing:
tensor([[-0.3902,  0.2747],
        [-0.5827,  0.4113]], requires_grad=True)
Parameter containing:
tensor([[ 1.0853,  0.0631],
        [-0.3021, -0.0524]], requires_grad=True)
